name: Build and deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['dev']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.12.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build
        run: |
          pnpm install
          pnpm build:client
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path:
            apps/client/dist/
            apps/client/dist/assets/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

